// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Projeto1_IF.Models;

public partial class TbContrato
{
    public int IdContrato { get; set; }

    [Display(Name = "Plano")]
    public int IdPlano { get; set; }

    public DateTime? DataInicio { get; set; }

    public DateTime? DataFim { get; set; }

    [Display(Name = "Plano")]
    public virtual TbPlano IdPlanoNavigation { get; set; }

    public virtual ICollection<TbProfissional> TbProfissionals { get; set; } = new List<TbProfissional>();
}