// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto1_IF.Models;

public partial class TbMedicamento
{
    public int IdMedicamento { get; set; }

    public int IdCategoriaMedicamento { get; set; }

    public string Nome { get; set; }

    public string Bula { get; set; }

    public byte[] BulaArquivo { get; set; }

    public virtual TbCategoriaMedicamento IdCategoriaMedicamentoNavigation { get; set; }
}