// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Humanizer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Projeto1_IF.Models;

public partial class TbPaciente
{
    public int IdPaciente { get; set; }

    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(15)]
    public string Rg { get; set; }

    [StringLength(15)]
    public string Cpf { get; set; }

    [Display(Name = "Data de Nascimento")]
    [DataType(DataType.Date)]
    public DateOnly DataNascimento { get; set; }

    [StringLength(100)]
    [Display(Name = "Nome do Responsável")]
    public string NomeResponsavel { get; set; }

    [StringLength(1)]
    public string Sexo { get; set; }

    [Range(1, 5)]
    public int Etnia { get; set; }

    [StringLength(100)]
    public string Endereco { get; set; }

    [StringLength(50)]
    public string Bairro { get; set; }

    [Display(Name = "Cidade")]
    public int? IdCidade { get; set; }

    [StringLength(25)]
    [Display(Name = "Telefone Residencial")]
    public string TelResidencial { get; set; }

    [StringLength(25)]
    [Display(Name = "Telefone Comercial")]
    public string TelComercial { get; set; }

    [StringLength(25)]
    [Display(Name = "Celular")]
    public string TelCelular { get; set; }

    [StringLength(30)]
    [Display(Name = "Profissão")]
    public string Profissao { get; set; }

    [Display(Name = "Atleta")]
    public bool? FlgAtleta { get; set; }

    [Display(Name = "Gestante")]
    public bool? FlgGestante { get; set; }

    [Display(Name = "Cidade")]
    public virtual TbCidade IdCidadeNavigation { get; set; }

    public virtual ICollection<TbAntropometrium> TbAntropometria { get; set; } = new List<TbAntropometrium>();

    public virtual ICollection<TbEscalaBristolPacienteConsultum> TbEscalaBristolPacienteConsulta { get; set; } = new List<TbEscalaBristolPacienteConsultum>();

    public virtual ICollection<TbExameXPaciente> TbExameXPacientes { get; set; } = new List<TbExameXPaciente>();

    public virtual ICollection<TbHistoriaPatologica> TbHistoriaPatologicas { get; set; } = new List<TbHistoriaPatologica>();

    public virtual ICollection<TbHistoricoAlimentarNutricional> TbHistoricoAlimentarNutricionals { get; set; } = new List<TbHistoricoAlimentarNutricional>();

    public virtual ICollection<TbHistoricoDoencaAtual> TbHistoricoDoencaAtuals { get; set; } = new List<TbHistoricoDoencaAtual>();

    public virtual ICollection<TbHistoricoSocialAlimentar> TbHistoricoSocialAlimentars { get; set; } = new List<TbHistoricoSocialAlimentar>();

    public virtual ICollection<TbHoraPacienteProfissional> TbHoraPacienteProfissionals { get; set; } = new List<TbHoraPacienteProfissional>();

    public virtual ICollection<TbMedicoPaciente> TbMedicoPacientes { get; set; } = new List<TbMedicoPaciente>();
}