// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto1_IF.Models;

public partial class TbPerguntum
{
    public int IdPergunta { get; set; }

    public int IdProfissional { get; set; }

    public string Nome { get; set; }

    public bool Ativo { get; set; }

    public virtual TbProfissional IdProfissionalNavigation { get; set; }

    public virtual ICollection<TbRastreamentoRespostum> TbRastreamentoResposta { get; set; } = new List<TbRastreamentoRespostum>();
}