// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Projeto1_IF.Models;

public partial class TbPlano
{
    [Display(Name = "Plano")]
    public int IdPlano { get; set; }

    [Display(Name = "Plano")]
    public string Nome { get; set; }

    public int Validade { get; set; }

    public decimal Valor { get; set; }

    public virtual ICollection<TbContrato> TbContratos { get; set; } = new List<TbContrato>();
}