// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Projeto1_IF.Models;

public partial class TbProfissional
{
    
    public int IdProfissional { get; set; }

    [Display(Name = "Área de Atuação")]
    public int? IdTipoProfissional { get; set; }

    [Display(Name = "Plano")]
    public int IdContrato { get; set; }

    [Display(Name = "Tipo de Acesso")]
    public int? IdTipoAcesso { get; set; }

    [Display(Name = "Cidade")]
    public int IdCidade { get; set; }

    [Required]
    [StringLength(128)]
    public string IdUser { get; set; }

    public string Nome { get; set; }

    public string Cpf { get; set; }

    [Display(Name = "Crm")]
    public string CrmCrn { get; set; }

    public string Especialidade { get; set; }

    public string Logradouro { get; set; }

    [Display(Name = "Número")]
    public string Numero { get; set; }

    public string Bairro { get; set; }

    public string Cep { get; set; }

    public string Cidade { get; set; }

    public string Estado { get; set; }

    public string Ddd1 { get; set; }

    public string Ddd2 { get; set; }

    public string Telefone1 { get; set; }

    public string Telefone2 { get; set; }

    public decimal? Salario { get; set; }

    [Display(Name = "Cidade")]
    public virtual TbCidade IdCidadeNavigation { get; set; }

    [Display(Name = "Plano")]
    public virtual TbContrato IdContratoNavigation { get; set; }

    public virtual TbTipoAcesso IdTipoAcessoNavigation { get; set; }

    public virtual ICollection<TbHoraPacienteProfissional> TbHoraPacienteProfissionals { get; set; } = new List<TbHoraPacienteProfissional>();

    public virtual ICollection<TbMedicoPaciente> TbMedicoPacientes { get; set; } = new List<TbMedicoPaciente>();

    public virtual ICollection<TbPerguntum> TbPergunta { get; set; } = new List<TbPerguntum>();

    public virtual ICollection<TbReceitaAlimentarPadrao> TbReceitaAlimentarPadraos { get; set; } = new List<TbReceitaAlimentarPadrao>();

    public virtual ICollection<TbReceitaMedicaPadrao> TbReceitaMedicaPadraos { get; set; } = new List<TbReceitaMedicaPadrao>();
}