// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Projeto1_IF.Models;

public partial class TbRastreamentoRespostum
{
    public int IdRastreamentoResposta { get; set; }

    public int IdPergunta { get; set; }

    public int VlrRespota { get; set; }

    public int IdParteCorpo { get; set; }

    public string Obs { get; set; }

    public virtual TbPerguntum IdPerguntaNavigation { get; set; }

    public virtual ICollection<TbRastreamentoMetabolico> TbRastreamentoMetabolicos { get; set; } = new List<TbRastreamentoMetabolico>();
}